function getsample(instrument);
    wav = '.wav';
    name = ['sample/',instrument,wav];
    [y,fs] = audioread(name);
    a = floor(length(y)/2);
    sample = y(a:a+60000,1);
    samp = '_samp';
    sampname = [instrument,samp,wav];
    % audiowrite(sampname,sample,fs);
    pitch = mod(findpitch(sample,fs),12);
    modifyC = turnpitch2wave(sample,0,pitch,20000);
    modifyC1 = turnpitch2wave(sample,1,pitch,20000);
    modifyD = turnpitch2wave(sample,2,pitch,20000);
    modifyD1 = turnpitch2wave(sample,3,pitch,20000);
    modifyE = turnpitch2wave(sample,4,pitch,20000);
    modifyF = turnpitch2wave(sample,5,pitch,20000);
    modifyF1 = turnpitch2wave(sample,6,pitch,20000);
    modifyG = turnpitch2wave(sample,7,pitch,20000);
    modifyG1 = turnpitch2wave(sample,8,pitch,20000);
    modifyA = turnpitch2wave(sample,9,pitch,20000);
    modifyA1 = turnpitch2wave(sample,10,pitch,20000);
    modifyB = turnpitch2wave(sample,11,pitch,20000);
    modifyC2 = turnpitch2wave(sample,12,pitch,20000);
    cd sample_all/;
    mkdir(instrument);
    cd (instrument)
    audiowrite(sampname,sample,fs);    
    name = 'C.wav';
    audiowrite(name,modifyC,fs);
    name = '#C.wav';
    audiowrite(name,modifyC1,fs);
    name = 'D.wav';
    audiowrite(name,modifyD,fs);
    name = '#D.wav';
    audiowrite(name,modifyD1,fs);
    name = 'E.wav';
    audiowrite(name,modifyE,fs);
    name = 'F.wav';
    audiowrite(name,modifyF,fs);
    name = '#F.wav';
    audiowrite(name,modifyF1,fs);
    name = 'G.wav';
    audiowrite(name,modifyG,fs);
    name = '#G.wav';
    audiowrite(name,modifyG1,fs);
    name = 'A.wav';
    audiowrite(name,modifyA,fs);
    name = '#A.wav';
    audiowrite(name,modifyA1,fs);
    name = 'B.wav';
    audiowrite(name,modifyB,fs);
    name = 'C_upper.wav';
    audiowrite(name,modifyC2,fs);
    cd ..;
    cd ..;